basePath: /msapi/compver
host: localhost:3000
info:
  contact:
    email: ortelius-dev@googlegroups.com
    name: Ortelius Google Group
  description: |-
    RestAPI for the ComponentVersion Object
    ![Release](https://img.shields.io/github/v/release/ortelius/scec-compver?sort=semver)
    ![license](https://img.shields.io/github/license/ortelius/scec-compver)

    ![Build](https://img.shields.io/github/actions/workflow/status/ortelius/scec-compver/build-push-chart.yml)
    [![MegaLinter](https://github.com/ortelius/scec-compver/workflows/MegaLinter/badge.svg?branch=main)](https://github.com/ortelius/scec-compver/actions?query=workflow%3AMegaLinter+branch%3Amain)
    ![CodeQL](https://github.com/ortelius/scec-compver/workflows/CodeQL/badge.svg)
    [![OpenSSF-Scorecard](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-compver/badge)](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-compver)

    ![Discord](https://img.shields.io/discord/722468819091849316)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ortelius v11 ComponentVersion Microservice
  version: 11.0.0
paths:
  /msapi/compver:
    get:
      consumes:
        - "*/*"
      description: Get a list of component versions for the user.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a List of Component Versions
      tags:
        - compver
    post:
      consumes:
        - application/json
      description: Create a new ComponentVersion and persist it
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Create a ComponentVersion
      tags:
        - compver
  /msapi/compver/:key:
    get:
      consumes:
        - "*/*"
      description: Get a compver details based on the _key or name.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a Component Version
      tags:
        - compver
swagger: "2.0"
